rancher:
  labels:
    io.rancher.os.after: docker
  restart: always
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  image: rancher/agent:v0.8.2
  command: ${RANCHER_REG_URL}
